backend:
  name: test-repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "test"
    label: "Test"
    folder: "content/test"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
